export type SortingBy =
  | 'Id'
  | 'Surname'
  | 'Login'
  | 'Role'
  | 'Name'
  | 'Alias'
  | 'DepartmentName'
  | 'DepartmentAlias'
  | 'Capacity'
  | 'RoomTypeAlias'
  | 'SpecTypeAlias'
  | 'SpecDegree'
  | 'CreatedDate'
  | 'IssueType'
  | 'IsAnonymous';
